# Generated by Django 5.0.3 on 2024-04-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumno_entregable_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
